---
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: "Include credentials"
      ansible.builtin.include_vars: ./vars/.credentials.yml

    - name: "Create proxy_default network"
      community.docker.docker_network:
        name: proxy_default
        attachable: true
        appends: true

    - name: "Deploy br0 network"
      community.docker.docker_network:
        name: br0
        driver: "ipvlan"
        attachable: false
        appends: true
        scope: local
        driver_options:
          parent: "{{ shim_parent_interface }}"
        ipam_driver_options: {}
        ipam_config: "{{ ipam_config }}"

    - name: "Create compose projects"
      community.docker.docker_compose_v2:
        project_name: "{{ item }}"
        definition: "{{ lookup('ansible.builtin.template', 'compose/' + item + '.yml.j2') | from_yaml }}"
        state: present 
      loop: "{{ projects | flatten(levels=1) }}"
        
