---
networks:
  default:
    name: DMZ
    external: true
  proxy_default:
    external: true

services:
  adguard:
    restart: unless-stopped
    volumes:
      - "{{ appdata_path }}/dns/adguard/work:/opt/adguardhome/work"
      - "{{ appdata_path }}/dns/adguard/conf:/opt/adguardhome/conf"
    networks:
      default:
        ipv4_address: "{{ compose.dns.ip }}"
      proxy_default:
    image: adguard/adguardhome:latest

