---
services:
  tailscaled:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - "{{ appdata_path }}/ts/tailscaled:/var/lib/tailscale"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TS_AUTHKEY: "{{ compose_secrets.ts.authkey }}"
      TS_HOSTNAME: "{{ compose.ts.hostname }}"
      TS_EXTRA_ARGS: "--accept-routes --advertise-exit-node --advertise-routes={{ compose.ts.advertise_routes }}"
  
